### ISSUE TITLE
%server::Lan instead of $server::lan

### ISSUE THREAD

**Issue by bansheerubber** [Elletra/bl-decompiled#1]
in `allGameScripts.cs` at line 5331, there is an if statement:
```
if (%server::Lan)
{
    return;
}
```
`%server::Lan` should probably be `$server::Lan`. not sure how curated this repo is, so this may actually be a bug with the game instead of a bug with the .dso decompiler

**Comment by Auios** [comment]
According to my friends, this looks like it actually is %server::lan. So the decompiler is correct. Badspot did a sloppy.

**Comment by Elletra** [comment]
Yeah this is actually how the code is. Badspot made an oopsy
